[project]
name = "AML_Mini_Project"
version = "0.1.0"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "scikit-learn",
    "tensorflow",
    "datasets",
    "transformers",
    "tf-keras",
    "typing"
]

readme = "README.md"
requires-python = ">=3.10"