#!/bin/bash

#SBATCH --job-name=berk_test
#SBATCH --output=cleaning.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=2   
#SBATCH --mem-per-cpu=8G
#SBATCH --time=0-06:00:00
#SBATCH --partition=scavenge
#SBATCH --mail-type=END

echo "Running on $(hostname):"
module load Anaconda3
module load TensorFlow/2.0.0-fosscuda-2019b-Python-3.7.4
eval "$(conda shell.bash hook)"
source /home/ivpe/.bashrc
conda activate chatbot
python hpc_clean.py